### ISSUE TITLE
`carbon_index` and `electricity_co2_emissions_factors` should be optional

### ISSUE THREAD

**Issue by shorowit** [resnet-us/hers-diagnostic-schema#11]
You cannot calculate a Carbon Index for some locations (like Alaska and Hawaii) as there are no emission factors for these locations, so these fields cannot be required.

**Comment by nealkruis** [comment]
What is the exact language in 301 regarding locations outside of the grid regions supported by Cambium? I can't find anything, but I thought I remember there being something. @pfairey do you know?

**Comment by shorowit** [comment]
"(Normative note) Where Cambium data are not available for the Rated Home location, the CO2e Index and projected CO2e emissions shall not be required."
