### ISSUE TITLE
Collect more info about IAD?

### ISSUE THREAD

**Issue by shorowit** [resnet-us/hers-diagnostic-schema#2]
Currently the schema has an `iad_save`, but no other information is collected for the IAD, making it hard to investigate discrepancies.

Alternatively, the schema could drop `iad_save` and software tools could provide _two_ diagnostic output files that reflect the schema -- one for the Rated Home (compared to the Reference Home) and one for the IAD Home (compared to its Reference Home).

@nealkruis

**Comment by nealkruis** [comment]
Addressed in #4.
